version: "3.3" # optional since v1.27.0
services:
  web:
    container_name: idp.server
    build: .
    ports:
      - "5001:80"
    links:
      - mssql
    depends_on:
      - mssql
    restart: unless-stopped
  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
